[sql]
host = "localhost"
port = "5432"
username = "postgres"
password = "a1b2c3d4"
database = "ahucmoj"
timezone = "Asia/Shanghai"

[server]
port = "1016"

[common]
languages = ["c", "cpp", "rust", "python"]
suffix = ["c", "cpp", "rs", "py"]

[compile]
c = "gcc -std=c17 -o $target $source"
cpp = "g++ -std=c++20 -o $target $source"
rust = "rustc -o $target $source"

[run]
c = "$target"
cpp = "$target"
rust = "$target"
python = "python3 $source"

[channel]
c = "stderr"
cpp = "stderr"
rust = "stdout"

[flags]
java = ["mem"]
