languages = ["c", "cpp", "rust", "python"]

[compile]
c = "gcc -std=c17 -o $target $source"
cpp = "g++ -std=c++20 -o $target $source"
rust = "rustc -o $target $source"

[run]
c = "$target"
cpp = "$target"
rust = "$target"
python = "python3 $source"

[channel]
c = "stderr"
cpp = "stderr"
rust = "stdout"
