[package]
name = "ahucm_oj_core"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.2"
log = { version = "0.4.21", features = ["std"] }
nix = { version = "0.28.0", features = ["process"] }
num_cpus = "1.16.0"
once_cell = "1.19.0"
toml = "0.8.10"
